ipc_socket = true
live_config_reload = true
working_directory = "None"

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

# [colors.search.footer_bar]
# background = "#A6ADC8"
# foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[cursor]
blink_interval = 1000
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 13

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Medium"

[font.bold]
family = "Jetbrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "Jetbrains Mono Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "asdfjkl"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "Y"
mods = "Control|Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[mouse]
hide_when_typing = true

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.92
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 3
y = 0
