add_newline = true
format = """
[󰮯  ](yellow)\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character
"""

right_format = """$cmd_duration"""

[character]
success_symbol = "[󰊠 ](green)"
error_symbol = "[󰊠 ](red)"

[directory]
truncation_length = 99
truncate_to_repo = false

[git_branch]
symbol = ""
format = 'on [$symbol $branch ](bold purple)'

[git_status]
staged = '++\($count\)'
ahead = "↑"
behind = "↓"
modified = "±"

