#!/bin/sh

# picom -b &

# for pipewire
pipewire &
pipewire-pulse &
wireplumber &
# equalizer for pipewire
easyeffects --gapplication-service &

# for pulseaudio
# pulseaudio --start --log-target=syslog &
monitor -r &
fcitx5 &
clipmenud  &
dunst &
unclutter --start-hidden --timeout 2 -f &
xrdb merge ~/.config/x11/Xresources_catppuccin &
# monitor -r &
feh --bg-fill --no-fehbg ~/personal/pictures/wall.png &

# run bar script and dwm ( do not remove this )
~/workspace/suckless/jondwm/bar/bar.sh &
dwm
